steps:
# meita-bucket-browser-block

- name: node:21.7.3
  entrypoint: yarn

- name: node:21.7.3
  entrypoint: yarn
  args: ['add', 'replace-in-files-cli', '-D']

- name: node:21.7.3
  entrypoint: yarn
  args: ['run', 'replace-in-files', '--regex="Version:.*"', '--replacement="Version:           $TAG_NAME"', 'meita-documents-and-media.php']

- name: node:21.7.3
  entrypoint: yarn
  args: ['run','cloudbuild']

- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'mv'
  args: [ 'build', 'meita-documents-and-media' ]

# Taged
- name: europe-north1-docker.pkg.dev/rauni-0/tools/zip
  args: ['-r9T', 'meita-documents-and-media-$TAG_NAME.zip', './meita-documents-and-media']

# Overwrite latest
- name: europe-north1-docker.pkg.dev/rauni-0/tools/zip
  args: ['-r9T', 'meita-documents-and-media-latest.zip', './meita-documents-and-media']

artifacts:
  objects:
    location: 'gs://wp-repository/plugins'
    paths: ['meita-documents-and-media-$TAG_NAME.zip', 'meita-documents-and-media-latest.zip']